-- =========================================================================
-- v20_order_lifecycle.sql
-- STEP 09: Order Lifecycle — audit trail trạng thái đơn + bổ sung columns
-- đối soát (RLS_MATRIX.md §24.1 "Mối quan hệ và columns trống").
--
-- Bổ sung:
--   orders         : + updated_by, submitted_at, submitted_by, failure_reason,
--                    + status TEXT -> ENUM-ish (giữ TEXT + CHECK lỏng để tương
--                    thích v15 trạng thái 'draft'/'processing'/'submitted')
--   submitted_orders: + status, failure_reason
--   order_events   : bảng sự kiện bất biến ghi mọi chuyển trạng thái đơn
--                    (không cho UPDATE/DELETE qua client)
-- RPC trợ giúp:
--   create_order_event(shop_id, order_id, event_type, event_status, old_status,
--                      new_status, meta TEXT, device_id, failure_reason)
--   -> dùng cho service_role/extension khi lưu sự kiện; guard thành viên.
-- =========================================================================

-- ---------------------------------------------------------------------
-- 1. Bổ sung columns orders
-- ---------------------------------------------------------------------
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES public.profiles(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS submitted_by UUID REFERENCES public.profiles(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS failure_reason TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS source_device_id TEXT;

-- Đảm bảo trạng thái bám khởi đầu: draft -> processing -> submitted
-- (giữ giá trị cũ như 'draft'); không ép CHECK cứng để tránh gãy luồng cũ.
-- ---------------------------------------------------------------------
-- 2. Bổ sung columns submitted_orders
-- ---------------------------------------------------------------------
ALTER TABLE public.submitted_orders ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'submitted';
ALTER TABLE public.submitted_orders ADD COLUMN IF NOT EXISTS failure_reason TEXT;
ALTER TABLE public.submitted_orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- ---------------------------------------------------------------------
-- 3. order_events — sổ bất biến của đơn
--    LƯU Ý KIỂU DỮ LIỆU: DB thực tế có orders.id kiểu TEXT (không UUID).
--    Vì vậy order_id/submitted_order_id dùng TEXT đồng bộ kiểu, KHÔNG gắn
--    FK cứng tới orders/submitted_orders để tránh lỗi 42804.
--    shop_id / user_id vẫn UUID như hệ thống chuẩn.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.order_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT,
    submitted_order_id TEXT,
    shop_id UUID REFERENCES public.shops(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id),
    event TEXT NOT NULL,
    status TEXT,
    before_status TEXT,
    after_status TEXT,
    meta JSONB,
    failure_reason TEXT,
    device_id TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Bảo vệ: mealy immutable -> không ai client được sửa/xóa dòng lịch sử
ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;

-- RLS: thành viên shop/owner/SYSTEM_ADMIN đọc events đơn của shop mình
DROP POLICY IF EXISTS "Members read order events" ON public.order_events;
CREATE POLICY "Members read order events" ON public.order_events
    FOR SELECT USING (
        public.is_shop_member(shop_id)
        OR public.is_system_admin()
    );

-- Chặn client ghi trực tiếp (ghi qua RPC service_role/extension)
DROP POLICY IF EXISTS "No client write order events" ON public.order_events;
CREATE POLICY "No client write order events" ON public.order_events
    FOR ALL USING (false);

REVOKE INSERT, UPDATE, DELETE ON public.order_events FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.order_events FROM anon;

-- Index trả sổ theo shop + thời gian
CREATE INDEX IF NOT EXISTS idx_order_events_shop_time
    ON public.order_events (shop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_events_order
    ON public.order_events (order_id);

-- ---------------------------------------------------------------------
-- 4. RPC ghi sự kiện qua service_role RPC có guard (không lộ trực tiếp)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_order_event(
    p_shop_id UUID,
    p_event TEXT,
    p_order_id TEXT DEFAULT NULL,
    p_submitted_order_id TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_before_status TEXT DEFAULT NULL,
    p_after_status TEXT DEFAULT NULL,
    p_meta JSONB DEFAULT NULL,
    p_failure_reason TEXT DEFAULT NULL,
    p_device_id TEXT DEFAULT NULL
) RETURNS public.order_events
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    ev public.order_events;
BEGIN
    -- Chỉ ch hợp pháp: thành viên shop đó HOẶC system admin
    IF NOT (public.is_shop_member(p_shop_id) OR public.is_system_admin()) THEN
        RAISE EXCEPTION 'ACCESS_DENIED';
    END IF;

    INSERT INTO public.order_events (
        shop_id, order_id, submitted_order_id, event, status,
        before_status, after_status, meta, failure_reason, device_id
    ) VALUES (
        p_shop_id, p_order_id, p_submitted_order_id, p_event, p_status,
        p_before_status, p_after_status, p_meta, p_failure_reason, p_device_id
    )
    RETURNING * INTO ev;

    RETURN ev;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_order_event(
    UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, TEXT, TEXT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_order_event(
    UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, TEXT, TEXT
) TO service_role;

-- ---------------------------------------------------------------------
-- GHI CHÚ:
--   - submitted_orders giờ có status để báo đơn submitted thành công hay
--     thất bại (tracking happened; failure_reason lưu lý do nếu lỗi).
--   - order_events bất biến qua RLS: chỉ RPC/SECURITY DEFINER ghi được.
--   - Nếu sau này cần enum cứng status: chạy 1 migration CONVERT type,
--     đừng sửa dữ liệu lịch sử.
-- =========================================================================